### ISSUE TITLE
License

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-site-eleventy#12]
The license text is missing the year: https://spdx.org/licenses/MIT.html

![image](https://github.com/conedevelopment/sprucecss-site-eleventy/assets/952007/ee629fa5-e57e-4da9-ac52-14765b1f7b03)

**Comment by szepeviktor** [comment]
It is easy to change the year in every January!

**Comment by adamlaki** [comment]
Thanks! I've removed the license altogether. In this type of project, it is better if it is not present.
