### ISSUE TITLE
Eleventy depends on API

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-site-eleventy#16]
When run locally, `npm run prod` errors out with

> Caching an already local asset is not yet supported.

https://github.com/conedevelopment/sprucecss-site-eleventy/blob/9e33cd6c4982f9585fef740a7285b81897ce36d6/src/_data/ui.js#L6-L9

**Comment by adamlaki** [comment]
That is interesting, it is run fine on my local environment.

**Comment by szepeviktor** [comment]
Do you have anything Eleventy related set up on your machine?

**Comment by szepeviktor** [comment]
in GitHub Actions: https://github.com/conedevelopment/sprucecss-site-eleventy/actions/runs/8123834359/job/22204658813

**Comment by adamlaki** [comment]
Ohh, yeah! The API URL comes from .env. How can I that on GH?

**Comment by szepeviktor** [comment]
#19 

It would be nice to run 100% locally, without any network traffic.
