### ISSUE TITLE
Outdated things in brand new repo

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-site-eleventy#2]
These are a bit old.
https://github.com/szepeviktor/sprucecss-site-eleventy/pulls

**Comment by szepeviktor** [comment]
Could be checked once a month with Dependabot.
https://github.com/szepeviktor/sprucecss-site-eleventy/blob/main/.github/dependabot.yml

**Comment by adamlaki** [comment]
Thank you! I think like this: https://github.com/conedevelopment/sprucecss-site-eleventy/commit/f408b80e8294e4e1cae1930b968b486b8dd96963, but the lint fails.

Dependabot looks good, can you send that PR?

**Comment by adamlaki** [comment]
Should I change `npm ci` to `npm install` in the workflow file?

**Comment by adamlaki** [comment]
Oh, on my local machine... :| I've updated the package.json but hadn't installed it. Thanks!

**Comment by szepeviktor** [comment]
> Dependabot looks good, can you send that PR?

#4
