### ISSUE TITLE
Undefined CSS classes

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-site-eleventy#25]
There are some undefined CSS classes on the front page.

![image](https://github.com/conedevelopment/sprucecss-site-eleventy/assets/952007/68eceaeb-dbf0-4812-8068-68d20f7fcec4)

Tool used: https://github.com/broofa/checkcss

... I see some of them are used in JavaScript.

**Comment by adamlaki** [comment]
@szepeviktor Hello Viktor,

finally here. This is intentional, I always declare a the classes for a component.
