### ISSUE TITLE
Validate editorconfig

### ISSUE THREAD

**Issue by adamlaki** [conedevelopment/sprucecss-site-eleventy#3]
@szepeviktor Viktor,

I have an interesting situation. In markdown I'd like to use for spaces but for code blocks (```) I need two spaces for scss. Do you have any idea how to validate this?

Now I set the .md-s to two spaces but it looks funny because the .yamllint and the .editorconfig stores two different indent size.

**Comment by szepeviktor** [comment]
EditorConfig is general, so it won't understand the contents of a file.
So files with mixed indentations should have `indent_size = unset`

[Markdownlint](https://github.com/szepeviktor/byte-level-care/blob/361131f10976e889fce51bba5775fd8040d0862b/.github/workflows/markdown.yml#L33-L45) could help https://github.com/DavidAnson/markdownlint/issues/312

**Comment by szepeviktor** [comment]
... or Prettier: https://github.com/prettier/prettier/issues/5971

**Comment by adamlaki** [comment]
I think you are right, the best is to simply use unset for indent_size, solves everything. I use it for HTML files under IDE folder right now and the yamllint will check the frontmetter.

Thank you!
