### ISSUE TITLE
Failed job

### ISSUE THREAD

**Issue by adamlaki** [conedevelopment/sprucecss-site-eleventy#35]
@szepeviktor do you have any idea what his could be: https://github.com/conedevelopment/sprucecss-site-eleventy/actions/runs/8594890221/job/23548709206 ?

The only thing I could find is some kind of memory problem with the server.

**Comment by szepeviktor** [comment]
Also in https://github.com/conedevelopment/sprucecss-site-eleventy/actions/runs/8592329829/job/23542182370

Yes, it must be a server thing.
