### ISSUE TITLE
HTML validation

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-site-eleventy#5]
Too much money for NOTHING 🙃 

![image](https://github.com/conedevelopment/sprucecss-site-eleventy/assets/952007/a78d0a0f-8d45-42cf-9eac-be0166d05f07)

**Comment by szepeviktor** [comment]
Could it be that Netlify has not yet deployed from this repo??
The production site is from https://github.com/conedevelopment/sprucecss-site ?

**Comment by adamlaki** [comment]
Viktor, 

yes, I will switch this site with the current one when it is ready (which is almost). The local environment is enough for testing because it is 98% the same.

**Comment by adamlaki** [comment]
@szepeviktor Viktor,

I've just checked the site with an HTML validator, and I didn't find anything interesting (mostly alpine.js stuff).

**Comment by szepeviktor** [comment]
@adamlaki The Blog page has two main-s: https://github.com/search?q=repo%3Aconedevelopment%2Fsprucecss-site-eleventy%20%3Cmain%20id%3D%22content%22&type=code

**Comment by szepeviktor** [comment]
I was shaking my body https://www.youtube.com/watch?v=V186RSgnO-Y while doing those validator clicks!

**Comment by adamlaki** [comment]
Thank you, Viktor! Fixed it!
